'use client';

import React, { useEffect, useRef, useState } from 'react';
import { Send, Download, FileText } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { backendFetch } from '@/lib/backend';

export interface ChatMessage {
  role: 'user' | 'assistant' | 'error';
  text: string;
  sources?: { tool: string; args: Record<string, unknown> }[];
  usedFallback?: boolean;
}

const TOOL_LABELS: Record<string, string> = {
  collections_summary: 'Collections',
  ward_summary: 'Ward summary',
  ward_parcels: 'Ward plots',
  defaulters: 'Defaulters',
  plot_lookup: 'Plot lookup',
  owner_lookup: 'Owner lookup',
  payments_in_period: 'Payment register',
  generate_analysis_pdf: 'Executive Analysis (PDF)',
  generate_report_pdf: 'Official Report (PDF)',
};

const EXAMPLES_BY_ROLE: Record<string, string[]> = {
  admin: [
    'Generate an executive analysis PDF report for 2026',
    'Export arrears & defaulters report as PDF',
    'How much have we collected this year, by ward?',
    'Which wards have the lowest collection rates?',
    'Who has been overdue for more than 60 days?',
    'Show me today\'s payment collections',
    'List plots in Karura ward that are unpaid',
    'Show history of plot 1865',
  ],
  auditor: [
    'Export arrears & defaulters report as PDF',
    'Generate collections report for 2026 as PDF',
    'Which plots in Karura ward are overdue?',
    'Who has been overdue for more than 90 days?',
    'Show payments received this month',
    'How much revenue is outstanding this year?',
  ],
  owner: [
    'Generate an executive analysis PDF for 2026',
    'Which counties have the highest collection rates?',
    'Show all years with unpaid bills',
    'Compare ward performance across sub-counties',
    'What is the total revenue collected to date?',
  ],
  default: [
    'How much have we collected this year?',
    'Who has been overdue for more than 60 days?',
    'Show the history of plot 1865',
    'Generate an executive analysis PDF for 2026',
  ],
};

const getExamples = (role?: string) =>
  EXAMPLES_BY_ROLE[role ?? 'default'] ?? EXAMPLES_BY_ROLE['default'];

const HISTORY_TURNS = 6; // matches max_length on the backend serializer
const MD_CELL = 'border-border-default border-[0.5px] px-2.5 py-1.5 text-left align-top';

export function AssistantMarkdown({ text }: { text: string }) {
  return (
    <div className="space-y-2 text-sm text-text-primary [&>*:first-child]:mt-0 [&>*:last-child]:mb-0">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          table: ({ children }) => (
            <div className="my-2 overflow-x-auto">
              <table className="w-full border-collapse text-[13px] tabular-nums">{children}</table>
            </div>
          ),
          thead: ({ children }) => <thead className="bg-hover-surface">{children}</thead>,
          th: ({ children }) => <th className={`${MD_CELL} font-medium text-text-secondary`}>{children}</th>,
          td: ({ children }) => <td className={MD_CELL}>{children}</td>,
          ul: ({ children }) => <ul className="list-disc space-y-1 pl-5">{children}</ul>,
          ol: ({ children }) => <ol className="list-decimal space-y-1 pl-5">{children}</ol>,
          p: ({ children }) => <p className="leading-relaxed">{children}</p>,
          strong: ({ children }) => <strong className="font-semibold">{children}</strong>,
          code: ({ children }) => (
            <code className="bg-hover-surface px-1 py-0.5 font-mono text-[12px]">{children}</code>
          ),
          a: ({ children, href }) => {
            const isPdf = href && (href.includes('/ai-download/') || href.includes('.pdf'));
            if (isPdf) {
              return (
                <div className="my-2.5 flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-none border border-neutral-300 bg-neutral-50 p-3 dark:border-neutral-700 dark:bg-neutral-900/60">
                  <div className="flex items-center gap-2.5 min-w-0">
                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-none bg-red-600 text-[10px] font-bold text-white tracking-wider">
                      PDF
                    </div>
                    <div className="min-w-0 flex-1">
                      <p className="text-xs font-semibold text-text-primary truncate">
                        {children || 'Download PDF Report'}
                      </p>
                      <p className="text-[11px] text-text-tertiary">Generated by E-Rates AI · Ready for download</p>
                    </div>
                  </div>
                  <a
                    href={href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex shrink-0 items-center justify-center gap-1.5 rounded-none bg-primary px-3 py-1.5 text-xs font-semibold text-white transition-opacity hover:opacity-90"
                  >
                    <Download className="h-3.5 w-3.5" />
                    <span>Download PDF</span>
                  </a>
                </div>
              );
            }
            return (
              <a
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2 hover:text-primary transition-colors"
              >
                {children}
              </a>
            );
          },
        }}
      >
        {text}
      </ReactMarkdown>
    </div>
  );
}

export function ThinkingIndicator() {
  return (
    <div className="self-stretch space-y-2 pl-4">
      <p className="text-xs text-text-tertiary">Looking up the data…</p>
      <div className="h-[2px] w-full overflow-hidden rounded-full bg-neutral-200 dark:bg-neutral-700">
        <div
          className="h-full w-1/2 rounded-full"
          style={{
            background: 'linear-gradient(90deg, transparent 0%, #6366f1 40%, #a855f7 60%, transparent 100%)',
            animation: 'ai-shimmer 1.4s ease-in-out infinite',
          }}
        />
      </div>
    </div>
  );
}

const sourceLabel = (s: { tool?: string; args?: Record<string, unknown> } | string) => {
  if (typeof s === 'string') return s;
  if (!s || typeof s !== 'object') return String(s ?? '');
  const args = s.args && typeof s.args === 'object' ? s.args : {};
  const detail = Object.entries(args)
    .filter(([, v]) => v !== '' && v !== null && v !== undefined)
    .map(([k, v]) => `${k} ${v}`)
    .join(', ');
  const toolName = (s.tool && TOOL_LABELS[s.tool]) || s.tool || 'Database';
  return `${toolName}${detail ? ` · ${detail}` : ''}`;
};

export function AssistantChat({ compact = false, userRole }: { compact?: boolean; userRole?: string }) {
  const [text, setText] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [sending, setSending] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setText(e.target.value);
    e.target.style.height = 'auto';
    e.target.style.height = `${e.target.scrollHeight}px`;
  };

  const send = async (preset?: string) => {
    const query = (preset ?? text).trim();
    if (!query || sending) return;
    const history = messages
      .filter((m) => m.role !== 'error' && m.text.trim())
      .slice(-HISTORY_TURNS)
      .map((m) => ({ role: m.role, text: m.text }));
    setMessages((m) => [...m, { role: 'user', text: query }]);
    setText('');
    if (textareaRef.current) textareaRef.current.style.height = 'auto';
    setSending(true);
    try {
      const response = await backendFetch('/api/llm/analyze/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query, history }),
      });
      const body = await response.json().catch(() => ({}));
      setMessages((m) => [
        ...m,
        response.ok
          ? { role: 'assistant', text: body.answer ?? '', sources: body.sources ?? [], usedFallback: !!body.used_fallback }
          : {
              role: 'error',
              text:
                response.status === 503
                  ? 'The assistant is offline. Set LLM_API_URL on the server to the running Colab link.'
                  : body.error || body.detail || `Request failed (${response.status})`,
            },
      ]);
    } catch (error) {
      setMessages((m) => [...m, { role: 'error', text: (error as Error).message }]);
    } finally {
      setSending(false);
    }
  };

  const pad = compact ? 'px-4 py-4' : 'px-6 py-6';
  const width = compact ? 'w-full' : 'mx-auto max-w-3xl';

  return (
    <>
      <div className={`flex-1 overflow-y-auto ${pad}`}>
        <div className={`flex flex-col gap-4 ${width}`}>
          {messages.length === 0 && (
            <div className={compact ? 'py-6' : 'py-16'}>
              <p className="text-sm font-medium text-text-primary">Ask about collections, defaulters, wards, plots or payments.</p>
              <p className="mt-1 text-xs text-text-tertiary">Answers come from live E-Rates data. The assistant can read but never change anything.</p>
              <div className="mt-4 flex flex-wrap gap-1.5">
                {getExamples(userRole).map((example) => (
                  <button
                    key={example}
                    onClick={() => send(example)}
                    className="rounded-full border border-neutral-300 bg-neutral-50 px-3 py-1 text-left text-xs text-text-secondary transition-colors hover:border-neutral-400 hover:bg-neutral-100 dark:border-neutral-700 dark:bg-neutral-800/60 dark:hover:border-neutral-600 dark:hover:bg-neutral-800"
                  >
                    {example}
                  </button>
                ))}
              </div>
            </div>
          )}
          {messages.map((message, i) =>
            message.role === 'user' ? (
              <div key={i} className="border-border-default self-end border-[0.5px] px-4 py-2.5 text-sm text-text-primary">
                {message.text}
              </div>
            ) : (
              <div key={i} className="self-stretch">
                <div
                  className={`border-l-2 pl-4 text-sm ${
                    message.role === 'error'
                      ? 'border-red-600 whitespace-pre-wrap text-red-700 dark:text-red-400'
                      : 'border-text-primary text-text-primary'
                  }`}
                >
                  {message.role === 'error' ? message.text : <AssistantMarkdown text={message.text} />}
                </div>
                {!!message.sources?.length && (
                  <p className="mt-2 pl-4 text-[11px] text-text-tertiary">
                    From: {message.sources.map(sourceLabel).join(' · ')}
                    {message.usedFallback && ' · picked by keyword match'}
                  </p>
                )}
              </div>
            )
          )}
          {sending && <ThinkingIndicator />}
          <div ref={bottomRef} />
        </div>
      </div>

      <div className={`border-border-default w-full shrink-0 border-t-[0.5px] ${compact ? 'px-4 py-3' : 'px-6 py-3'}`}>
        <div className={`border-border-default focus-within:border-text-tertiary flex w-full items-end gap-3 border-[0.5px] px-3 py-1.5 text-[14px] text-text-primary transition-colors ${width}`}>
          <textarea
            ref={textareaRef}
            value={text}
            onChange={handleInput}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                send();
              }
            }}
            placeholder="Ask the E-Rates assistant"
            rows={1}
            className="max-h-[200px] w-full flex-1 resize-none bg-transparent py-2 placeholder:text-text-tertiary focus:outline-none"
          />
          <button
            onClick={() => send()}
            disabled={!text.trim() || sending}
            aria-label="Send"
            className="mb-1 bg-text-primary p-2 text-main-bg transition-opacity disabled:opacity-30"
          >
            <Send className="h-4 w-4" />
          </button>
        </div>
        <p className={`mt-1.5 text-[10px] text-text-tertiary ${width}`}>
          Answers can be wrong. Check figures against Reports before acting on them.
        </p>
      </div>
    </>
  );
}
