export const nairobiSubCounties = [
  { value: 'westlands', label: 'Westlands' },
  { value: 'dagoretti-north', label: 'Dagoretti North' },
  { value: 'dagoretti-south', label: 'Dagoretti South' },
  { value: 'langata', label: 'Langata' },
  { value: 'kibra', label: 'Kibra' },
  { value: 'roysambu', label: 'Roysambu' },
  { value: 'kasarani', label: 'Kasarani' },
  { value: 'ruaraka', label: 'Ruaraka' },
  { value: 'embakasi-south', label: 'Embakasi South' },
  { value: 'embakasi-north', label: 'Embakasi North' },
  { value: 'embakasi-central', label: 'Embakasi Central' },
  { value: 'embakasi-east', label: 'Embakasi East' },
  { value: 'embakasi-west', label: 'Embakasi West' },
  { value: 'makadara', label: 'Makadara' },
  { value: 'kamukunji', label: 'Kamukunji' },
  { value: 'starehe', label: 'Starehe' },
  { value: 'mathare', label: 'Mathare' },
];
