export const nairobiWards = [
  { value: 'kangemi', label: 'Kangemi' },
  { value: 'mountain-view', label: 'Mountain View' },
  { value: 'parklands-highridge', label: 'Parklands/Highridge' },
  { value: 'karura', label: 'Karura' },
  { value: 'kitisuru', label: 'Kitisuru' },
  { value: 'kawangware', label: 'Kawangware' },
  { value: 'gatina', label: 'Gatina' },
  { value: 'kileleshwa', label: 'Kileleshwa' },
  { value: 'kilimani', label: 'Kilimani' },
  { value: 'karen', label: 'Karen' },
  { value: 'nairobi-west', label: 'Nairobi West' },
  { value: 'mugumo-ini', label: 'Mugumo-ini' },
  { value: 'south-c', label: 'South C' },
  { value: 'nyayo-highrise', label: 'Nyayo Highrise' },
  { value: 'laini-saba', label: 'Laini Saba' },
  { value: 'lindi', label: 'Lindi' },
  { value: 'makina', label: 'Makina' },
  {
    value: 'woodley-kenyatta-golf-course',
    label: 'Woodley/Kenyatta Golf Course',
  },
  { value: 'sarang-ombe', label: "Sarang'ombe" },
  { value: 'zimmerman', label: 'Zimmerman' },
  { value: 'roysambu', label: 'Roysambu' },
  { value: 'kahawa-west', label: 'Kahawa West' },
  { value: 'githurai', label: 'Githurai' },
  { value: 'kahawa', label: 'Kahawa' },
  { value: 'clay-city', label: 'Clay City' },
  { value: 'mwiki', label: 'Mwiki' },
  { value: 'kasarani', label: 'Kasarani' },
  { value: 'njiru', label: 'Njiru' },
  { value: 'ruai', label: 'Ruai' },
  { value: 'babadogo', label: 'Babadogo' },
  { value: 'utalii', label: 'Utalii' },
  { value: 'mathare-north', label: 'Mathare North' },
  { value: 'lucky-summer', label: 'Lucky Summer' },
  { value: 'korogocho', label: 'Korogocho' },
  { value: 'dandora-area-i', label: 'Dandora Area I' },
  { value: 'dandora-area-ii', label: 'Dandora Area II' },
  { value: 'dandora-area-iii', label: 'Dandora Area III' },
  { value: 'dandora-area-iv', label: 'Dandora Area IV' },
  { value: 'kayole-north', label: 'Kayole North' },
  { value: 'kayole-central', label: 'Kayole Central' },
  { value: 'kayole-south', label: 'Kayole South' },
  { value: 'komarock', label: 'Komarock' },
  { value: 'matopeni-spring-valley', label: 'Matopeni/Spring Valley' },
  { value: 'upper-savannah', label: 'Upper Savannah' },
  { value: 'lower-savannah', label: 'Lower Savannah' },
  { value: 'embakasi', label: 'Embakasi' },
  { value: 'utawala', label: 'Utawala' },
  { value: 'mihango', label: 'Mihango' },
  { value: 'imara-daima', label: 'Imara Daima' },
  { value: 'kwa-njenga', label: 'Kwa Njenga' },
  { value: 'kwa-reuben', label: 'Kwa Reuben' },
  { value: 'pipeline', label: 'Pipeline' },
  { value: 'kware', label: 'Kware' },
  { value: 'maringo-hamza', label: 'Maringo/Hamza' },
  { value: 'viwandani', label: 'Viwandani' },
  { value: 'harambee', label: 'Harambee' },
  { value: 'makongeni', label: 'Makongeni' },
  { value: 'pumwani', label: 'Pumwani' },
  { value: 'eastleigh-north', label: 'Eastleigh North' },
  { value: 'eastleigh-south', label: 'Eastleigh South' },
  { value: 'airbase', label: 'Airbase' },
  { value: 'nairobi-central', label: 'Nairobi Central' },
  { value: 'ngara', label: 'Ngara' },
  { value: 'pangani', label: 'Pangani' },
  { value: 'ziwani-kariokor', label: 'Ziwani/Kariokor' },
  { value: 'landimawe', label: 'Landimawe' },
  { value: 'nairobi-south', label: 'Nairobi South' },
  { value: 'hospital', label: 'Hospital' },
  { value: 'mabatini', label: 'Mabatini' },
  { value: 'huruma', label: 'Huruma' },
  { value: 'kiamaiko', label: 'Kiamaiko' },
  { value: 'ngei', label: 'Ngei' },
  { value: 'mlango-kubwa', label: 'Mlango Kubwa' },
];
